name: Trivy Example

on:
  # schedule:
    # run every Wednesday at 23:20
    # - cron: '20 23 * * 3'
  workflow_dispatch:


jobs:
  trivy_analysis:
    name: Trivy Analysis of Indy Node Images
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        os_version: [ ubuntu18 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy on indy_node:${{ matrix.os_version }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/idunion/indy-node-container/indy_node:latest-${{ matrix.os_version }}'
          format: 'json'
          output: 'trivy_example.txt'
          ignore-unfixed: true
          severity: 'CRITICAL'
      
      - name: Patch tool name for ${{ matrix.os_version }} scan
        run: |
          sed -i 's/"name": "Trivy",/"name": "Trivy${{ matrix.os_version }}Latest",/g' trivy_example.txt
      - name: 'trivy_example.txt'
        uses: actions/upload-artifact@v2
        with:
          name: trivy_example.txt
          path: trivy_example.txt
          retention-days: 8
