name: Trivy Example

on:
  workflow_dispatch:


jobs:
  trivy_analysis:
    name: Trivy Analysis of Indy Node Images
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        os_version: [ ubuntu18 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Trivy on indy_node:${{ matrix.os_version }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/zickau/indy-node-container/indy_node:latest-${{ matrix.os_version }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'
